language: python
python:
  - 3.6

install:
  - pip install pytest
  - pip install pycodestyle
  - pip install -U twine

script:
  - python setup.py sdist
  - twine upload dist/*

deploy:
  provider: script
  script:
    - python setup.py sdist
    - twine upload dist/*
  on:
    branch: asyncio
