language: python

python:
  - 3.6

install:
  - pip install pytest
  - pip install pycodestyle

deploy:
  provider: pypi
  user: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    branch: asyncio
